name: monokera_airflow
services:
  airflow-standalone:
    # In order to add custom dependencies or upgrade provider packages you can use your extended image.
    # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
    # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
    # image: apache/airflow:2.8.1
    build: .
    environment:
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    volumes:
      - ./airflow:/opt/airflow
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./raw:/opt/airflow/raw
      - ./staging:/opt/airflow/staging
      - ./expectations:/opt/airflow/expectations
      - ./state:/opt/airflow/state

    ports:
      - "8080:8080"
    command: airflow standalone
